CREATE TABLE IF NOT EXISTS Players (
    ID BIGINT PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    name VARCHAR(255) DEFAULT 'Guest',
    name_set BOOLEAN DEFAULT FALSE,
    gems INT DEFAULT 0,
    coins INT DEFAULT 0,
    box_tokens INT DEFAULT 0,
    big_box_tokens INT DEFAULT 0,
    trophies INT DEFAULT 0,
    tickets INT DEFAULT 0,
    token_doubler INT DEFAULT 0,
    highest_trophies INT DEFAULT 0,
    home_brawler INT DEFAULT 0,
    trophy_road_reward INT DEFAULT 1,
    experience_points INT DEFAULT 0,
    profile_icon INT DEFAULT 0,
    name_color INT DEFAULT 0,
    selected_brawler INT DEFAULT 0,
    region VARCHAR(10) DEFAULT 'BR',
    supported_content_creator VARCHAR(255) DEFAULT '',
    starpower INT DEFAULT 0,
    gadget INT DEFAULT 0,
    brawl_pass_activated BOOLEAN DEFAULT FALSE,
    welcome_message_viewed BOOLEAN DEFAULT FALSE,
    brawlers_unlocked JSON,
    brawlers_trophies JSON,
    brawlers_highest_trophies JSON,
    brawlers_level JSON,
    brawlers_power_points JSON,
    unlocked_skins JSON,
    selected_skins JSON,
    map_id INT DEFAULT 0,
    use_gadget BOOLEAN DEFAULT TRUE,
    home_skin INT DEFAULT 0,
    leaderboard_type INT DEFAULT 0,
    leaderboard_is_global BOOLEAN DEFAULT FALSE,
    brawlers_card_id JSON,
    brawlers_spg JSON,
    club_id BIGINT DEFAULT 0,
    club_role INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Clubs (
    ID BIGINT PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    region VARCHAR(10),
    badge_id INT DEFAULT 0,
    type INT DEFAULT 0,
    trophies INT DEFAULT 0,
    required_trophies INT DEFAULT 0,
    family_friendly BOOLEAN DEFAULT 0,
    members JSON,
    messages JSON
);
