CREATE TABLE IF NOT EXISTS Players (
    ID BIGINT PRIMARY KEY,
    Token VARCHAR(255) NOT NULL,
    Name VARCHAR(255) DEFAULT 'Guest',
    NameSet BOOLEAN DEFAULT FALSE,
    Gems INT DEFAULT 0,
    Trophies INT DEFAULT 0,
    Tickets INT DEFAULT 0,
    Resources JSON,
    TokenDoubler INT DEFAULT 0,
    HighestTrophies INT DEFAULT 0,
    HomeBrawler INT DEFAULT 0,
    TrophyRoadReward INT DEFAULT 1,
    ExperiencePoints INT DEFAULT 0,
    ProfileIcon INT DEFAULT 0,
    NameColor INT DEFAULT 0,
    UnlockedBrawlers JSON,
    BrawlersTrophies JSON,
    BrawlersHighestTrophies JSON,
    BrawlersLevel JSON,
    BrawlersPowerPoints JSON,
    UnlockedSkins JSON,
    SelectedSkins JSON,
    SelectedBrawler INT DEFAULT 0,
    Region VARCHAR(10) DEFAULT 'BR',
    SupportedContentCreator VARCHAR(255) DEFAULT 'Classic Brawl',
    StarPower INT DEFAULT 0,
    Gadget INT DEFAULT 0,
    BrawlPassActivated BOOLEAN DEFAULT FALSE,
    WelcomeMessageViewed BOOLEAN DEFAULT FALSE,
    ClubID BIGINT DEFAULT 0,
    ClubRole INT DEFAULT 1,
    TimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Clubs (
    ID BIGINT PRIMARY KEY,
    Name VARCHAR(255),
    Description TEXT,
    Region VARCHAR(10),
    BadgeID INT DEFAULT 0,
    Type INT DEFAULT 0,
    Trophies INT DEFAULT 0,
    RequiredTrophies INT DEFAULT 0,
    FamilyFriendly BOOLEAN DEFAULT 0,
    Members JSON,
    Messages JSON
);
